# Generated by Django 2.1 on 2018-08-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='adult',
            field=models.CharField(max_length=99),
        ),
    ]
