# Generated by Django 2.1 on 2018-08-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180812_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
