# Generated by Django 2.1 on 2018-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_delete_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=999)),
                ('id_movie', models.CharField(max_length=999)),
                ('original_title', models.CharField(max_length=999)),
                ('poster_path', models.CharField(max_length=999)),
                ('production_countries', models.CharField(max_length=999)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
